postgres:
  uri: "postgres://postgres:password@localhost:5432/photon-gun"
  min_connections: 1
  max_connections: 5

basic_checks:
  - id: 0
    name: google
    endpoint: "https://google.com"
    interval: 1

  - id: 0
    name: vorona
    endpoint: "https://vorona.gg/healthcheck"
    interval: 1

luxury_checks:
  - id: 0
    name: test
    script: "test.lua"
    interval: 5

  - id: 0
    name: random
    script: "random.lua"
    interval: 1
