[package]
name = "photon-gun"
authors = ["Devon Tingley <dtingley@twilit.io>"]
description = "Basic and Lua-Scriptable HTTP Monitor."
license = "MIT"
version = "0.1.0"
edition = "2021"

[dependencies]
hlua = "0.4.1"

tokio = {version = "1.17.0", features = ["rt","time","macros","signal"] }
reqwest = { version = "0.11.10", features = ["blocking"] }
tracing = "0.1.32"
tracing-subscriber = "0.3.9"

clap = { version = "3.1.6", features = ["derive"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_yaml = "0.8.23"
sqlx = { version = "0.5.11", features = ["postgres","runtime-tokio-rustls"] }

[profile.release]
lto = true
strip = true
