[package]
name = "photon-gun"
version = "0.1.0"
edition = "2021"

[dependencies]
hlua = "0.4.1"

tokio = {version = "1.17.0", features = ["full"] }
reqwest = "0.11.10"
tracing = "0.1.32"
tracing-subscriber = {version = "0.3.9", features = ["env-filter"] }
tokio-postgres = "0.7.5"

serde = { version = "1.0.136", features = ["derive"] }
serde_yaml = "0.8.23"
