version: 2.1

jobs:
  lint-and-test:
    docker:
      - image: rust
    steps:
      - checkout
      - run: "apt update && apt install -y cmake protobuf-compiler"
      - run: "cargo fmt"
      - run: "cargo clippy -- -D warnings"
      - run: "cargo test"

workflows:
  default:
    jobs:
      - lint-and-test
