name: Lint, Build, and Test

on: [push]

jobs:
  default:
    name: Lint, Build, and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Install Rust Stable
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Lint
        run: cargo fmt

      - name: Clippy
        run: cargo clippy

      - name: Test
        run: cargo test
